### ISSUE TITLE
question about train data annotation receipt_00734.json

### ISSUE THREAD

**Issue by Senwang98** [clovaai/cord#7]
hi, @ClovaAIAdmin 
I feel confused about annotation of train-00734.json.
<img width="442" alt="image" src="https://user-images.githubusercontent.com/23122139/176104494-90c3c520-cc66-4113-b5ef-37bfa6a9479d.png">
The height of image is 576, why the annotation is 578?

**Comment by eleventh83** [comment]
AFAIK, the coordinates can be outside of the image. This may be because data labeling tools are designed that way. We usually address this issue in the following way: After projecting the coordinates outside the image onto the edges of the image, a new quadrilateral is created based on the coordinates. You can use the new quadrilateral.
